### PR TITLE
Split into separate core, server, example packages

### PR DESCRIPTION
**Pull request by dbaynard**

### CODE REVIEW

**Comment by dbaynard** [comment]
Whoops, I included b12e102 which updates the resolver — I can rebase if desired

**Comment by ch1bo** [comment]
Can you merge `master` back into this to have travis builds check it

**Comment by dbaynard** [comment]
Build failures… I thought that might have happened. Travis now needs updating to reflect the new layout.

**Comment by ch1bo** [comment]
I fixed the `.travis.yml` in `ch1bo/servant-exceptions:feat/split-modules` opened as PR #7

**Pull request merged**
